import pynooj
import json


def group_inflected_forms_by_lemma(inflected_forms):
    """Group the inflected forms by lemma (verb)"""
    lemmas = {}
    for inflected_form in inflected_forms:
        lemma = inflected_form["lemma"]
        if lemma not in lemmas:
            lemmas[lemma] = []
        lemmas[lemma].append(inflected_form)
    return lemmas


def check_inflected_forms(inflected_forms):
    """Verify that all the necessary mood/voice/tense/person combinations have been generated by NooJ"""
    lemmas = group_inflected_forms_by_lemma(inflected_forms)

    missing = {}  # Should exist but not found
    extras = {}  # Found but should not exist

    for inflected_forms in sorted(lemmas.values(), key=lambda x: x[0]["group"]):
        group = inflected_forms[0]["group"]
        lemma = inflected_forms[0]["lemma"]

        if group == 0:
            continue
        for mood in ["indicatif", "subjonctif"]:
            for voice in ["actif", "passif"]:
                for tense in [
                    "présent",
                    "imparfait",
                    "futur",
                    "parfait",
                    "plus-que-parfait",
                    "futur antérieur",
                ]:
                    for person in [1, 2, 3, 4, 5, 6]:
                        key = f"group={group}, mood={mood}, voice={voice}, tense={tense}, person={person}"

                        if (
                            lemma == "timere"
                            and voice == "passif"
                            and (
                                tense == "parfait"
                                or tense == "plus-que-parfait"
                                or tense == "futur antérieur"
                            )
                        ):
                            continue

                        exist = False
                        for inflected_form in inflected_forms:
                            if (
                                inflected_form["person"] == person
                                and inflected_form["mood"] == mood
                                and inflected_form["voice"] == voice
                                and inflected_form["tense"] == tense
                            ):
                                exist = True

                        if mood == "subjonctif" and (
                            tense == "futur" or tense == "futur antérieur"
                        ):
                            if exist:
                                extras.setdefault(key, [])
                                extras[key].append(lemma)
                        else:
                            if not exist:
                                missing.setdefault(key, [])
                                missing[key].append(lemma)

    if len(missing) or len(extras):
        for key, lemmas in extras.items():
            print("should not exist:", key, lemmas)
        for key, lemmas in missing.items():
            print("missing:", key, lemmas)

            raise Exception(
                f"{len(missing)} missing forms and {len(extras)} extra forms"
            )


def main():
    verbs_lst = []
    dic_path = "NooJ/lat_verbes-flx.dic"
    print("reading verbs from NooJ dic:", dic_path)
    dics_nooj = pynooj.read_dic(dic_path)
    print(f"loaded {len(dics_nooj)} inflected forms (lines)")

    for dic_nooj in dics_nooj:
        dic_mc = {}
        try:
            dic_mc["latin"] = (
                dic_nooj["inflected form"].replace("v", "u").replace("j", "i")
            )
            dic_mc["lemma"] = dic_nooj["lemma"].replace("v", "u").replace("j", "i")
            dic_mc["group"] = int(dic_nooj["traits"]["GP"])
            dic_mc["mood"] = (
                dic_nooj["traits"]["MOD"]
                .replace("ind", "indicatif")
                .replace("sub", "subjonctif")
            )
            dic_mc["voice"] = (
                dic_nooj["traits"]["VX"]
                .replace("act", "actif")
                .replace("pas", "passif")
            )
            dic_mc["translation"] = dic_nooj["traits"]["TRAD"].split(";")
            dic_mc["primitive tenses"] = dic_nooj["traits"]["PRIM"].replace(";", ", ")

            # Convert to (French) human-readable tense (fut --> futur)
            match dic_nooj["traits"]["TP"]:
                case "fut":
                    dic_mc["tense"] = "futur"
                case "impf":
                    dic_mc["tense"] = "imparfait"
                case "pres":
                    dic_mc["tense"] = "présent"
                case "pft":
                    dic_mc["tense"] = "parfait"
                case "pqp":
                    dic_mc["tense"] = "plus-que-parfait"
                case "fta":
                    dic_mc["tense"] = "futur antérieur"
                case _:
                    raise ValueError("Invalid form, the tense is invalid")

            dic_mc["person"] = int(dic_nooj["traits"]["P"])
            if dic_mc["person"] not in range(1, 4):
                raise ValueError("Invalid form, the person is invalid")
            if dic_nooj["traits"]["NB"] == "pl":
                dic_mc["person"] += 3
            verbs_lst.append(dic_mc)
        except Exception as e:
            print("Error with:", dic_nooj)
            raise e

    # Sort by lemma > mood > voice > tense > person
    verbs_lst = sorted(
        verbs_lst,
        key=lambda x: (x["lemma"], x["mood"], x["voice"], x["tense"], x["person"]),
    )

    # Verify that all the necessary mood/voice/tense/person combinations have been generated by NooJ
    check_inflected_forms(verbs_lst)

    # Filter out some invalid inflected forms.
    filtered_verbs = []
    for inflected_form in verbs_lst:
        if (
            inflected_form["person"] == 2
            and inflected_form["mood"] == "indicatif"
            and inflected_form["voice"] == "passif"
        ):
            if (
                inflected_form["group"] == 1
                or inflected_form["group"] == 2
                and inflected_form["tense"] == "futur"
            ) or (
                inflected_form["group"] == 3
                or inflected_form["group"] == 4
                and inflected_form["tense"] == "présent"
            ):
                if inflected_form["latin"][-4:] == "iris":
                    # print(inflected_form["latin"])
                    continue
        filtered_verbs.append(inflected_form)

    json_path = "verbs_latin.json"
    print(f"writing {len(filtered_verbs)} verbs to json file:", json_path)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(filtered_verbs, f, indent=2, ensure_ascii=False)

    js_path = "verbs_latin.js"
    # Generated for static hosting: allows loading data without fetch/CORS on GitHub Pages.
    print(f"writing {len(filtered_verbs)} verbs to js file:", js_path)
    with open(js_path, "w", encoding="utf-8") as f:
        payload = "window.VERBS_LATIN = " + json.dumps(
            filtered_verbs, ensure_ascii=False
        )
        f.write(payload + ";\n")


if __name__ == "__main__":
    main()
